### PR TITLE
298 ux bugs

### LINKED ISSUE #298: Non-critical UX bugs
Let's collect here all non-critical UX bugs

1. by @AdrianDobrican 
Staging:

Figma:

2. by @AdrianDobrican 
Staging:

Figma:

3. by @AdrianDobrican 
Staging:

Figma:

4. Staging:
Image

Figma:
Image

### PR DESCRIPTION
**Pull request by Okekejr**
Fixes #298

Fixed UX issues on the Cards, Added text to the deposit modal, replaced (-)

## Screenshots (if appropriate):
<----- Aave text fix ------>

Screenshot 2022-07-22 at 2 28 58

<----- Text to deposit modal ------>

Screenshot 2022-07-22 at 2 29 22

<----- Replacing ------>

Screenshot 2022-07-22 at 2 29 45

<----- Breadcrumb update ----->

Screenshot 2022-07-22 at 9 45 02

## Links
https://www.figma.com/file/7IAQbLyzapnrow9sIcO77P/App?node-id=601%3A21278

### CODE REVIEW

File: src/components/_pages/PageCellar.tsx [hunk 1]
```diff
@@ -131,22 +133,34 @@ const PageCellar: VFC<CellarPageProps> = ({ data: staticData }) => {
           <VStack spacing={6} align="flex-start">
             <BreadCrumb cellarName={name} />
             <HStack spacing={4}>
-              <Link href="/">
+              {/* <Link href="/">
```
Comment (RyanWarner) [inline src/components/_pages/PageCellar.tsx:136]: Can this be safely deleted, or is it commented out for a reason? If there's a reason, could we add that to the comment?

File: src/components/_pages/PageCellar.tsx [hunk 2]
```diff
@@ -131,22 +133,34 @@ const PageCellar: VFC<CellarPageProps> = ({ data: staticData }) => {
...
+                  src="/assets/images/coin.png"
+                  width="40px"
+                  mb={3}
+                />
+                <Heading fontSize="2.5rem">
+                  {nameAbbreviated}{" "}
+                  <Box
+                    as="span"
+                    textTransform="uppercase"
+                    fontSize="21px"
```
Comment (RyanWarner) [inline src/components/_pages/PageCellar.tsx:157]: Avoid using pixel values for font sizes.

Preferably, use Chakra theme sizes. If this is a one off, use rems.

File: src/components/_pages/PageCellar.tsx [hunk 3]
```diff
@@ -131,22 +133,34 @@ const PageCellar: VFC<CellarPageProps> = ({ data: staticData }) => {
...
-              </Heading>
+              </Link> */}
+              <Box
+                display="flex"
+                width="15rem"
+                justifyContent="space-between"
+                alignContent="center"
+              >
+                <Img
+                  src="/assets/images/coin.png"
```
Comment (RyanWarner) [inline src/components/_pages/PageCellar.tsx:148]: Nitpick, but we could support `webp` images here, just like on the marketing site.

Comment (xanderjl) [reply src/components/_pages/PageCellar.tsx:142]: Good shout, but this could/should be a separate ticket, as all assets across the site are only pngs 😅 

I'll get a new issue opened!

**Review by xanderjl — APPROVED** [review]
This all looks great to me. Great work @Okekejr ! 🚀
