### PR TITLE
fix: apy chart for ryeth detail page

### LINKED ISSUE #1047: Fix APY chart for Real Yield ETH details page

### PR DESCRIPTION
**Pull request by joshuanatanielnm**
Fixes #1047 

## Description

Enable and fix chat for real yield eth in detail page

## Changes

List any technical changes.

- [fix: apy chart for ryeth detail page](https://github.com/strangelove-ventures/sommelier/commit/cb1dc7b743ccd92f6e8491983301578de48860b0)

### CODE REVIEW

File: src/data/context/apyChartContext.tsx [hunk 1]
```diff
@@ -166,9 +162,15 @@ export const ApyChartProvider: FC<{
...
-  const launchDate = Object.values(cellarDataMap).find(
+  const cellarData = Object.values(cellarDataMap).find(
     (item) => item.config.cellar.address === address
-  )?.launchDate!
+  )
+  const launchDate = cellarData?.launchDate!
+  const [{ data: sgData }] = useGetStrategyDataQuery({
+    variables: { cellarAddress: address.toLowerCase() },
+  })
+  const getDecimals = sgData?.cellar?.asset.decimals ?? 18
```
Comment (codingki) [inline src/data/context/apyChartContext.tsx:172]: non blocking the merge but this "get..." name is a variable not a function. Better rename this to `sgDecimals`

File: src/data/context/apyChartContext.tsx [hunk 2]
```diff
@@ -166,9 +162,15 @@ export const ApyChartProvider: FC<{
     apy: true,
   })
   const [timeline, setTimeline] = useState<Timeline>("1W")
-  const launchDate = Object.values(cellarDataMap).find(
+  const cellarData = Object.values(cellarDataMap).find(
     (item) => item.config.cellar.address === address
-  )?.launchDate!
+  )
+  const launchDate = cellarData?.launchDate!
+  const [{ data: sgData }] = useGetStrategyDataQuery({
```
Comment (codingki) [inline src/data/context/apyChartContext.tsx:169]: we have `useStrateyData` please use that instead this subgraph. so it's not refetching

File: src/data/context/apyChartContext.tsx (hunk 1 above)
Comment (codingki) [reply src/data/context/apyChartContext.tsx:172]: fallback value better `6` because we have only one strategy that underlying asset is eth

**Review by codingki — CHANGES_REQUESTED** [review]

**Review by codingki — APPROVED** [review]

**Review by asaadam — APPROVED** [review]
